---
# Full deployment playbook including SSL
- name: Deploy LiteLLM with SSL
  hosts: litellm_servers
  become: yes

  pre_tasks:
    - name: Update apt cache
      apt:
        update_cache: yes
        cache_valid_time: 3600
      when: ansible_os_family == "Debian"
      tags: [common, packages]

  roles:
    - role: common
      tags: [common]
    
    - role: geerlingguy.docker
      tags: [docker]
    
    - role: geerlingguy.nginx
      tags: [nginx]
    
    - role: litellm
      tags: [litellm]
    
    - role: ssl
      tags: [ssl, nginx]

  post_tasks:
    - name: Verify Nginx is running
      service:
        name: nginx
        state: started
        enabled: yes
      tags: [verify]

    - name: Verify LiteLLM service is running
      service:
        name: "{{ app_name }}"
        state: started
        enabled: yes
      tags: [verify]
    
    - name: Check SSL certificate validity
      shell: "openssl x509 -in /etc/letsencrypt/live/{{ domain_name }}/cert.pem -noout -dates"
      register: cert_dates
      changed_when: false
      tags: [verify]
    
    - name: Show certificate dates
      debug:
        var: cert_dates.stdout_lines
      tags: [verify]
    
    - name: Run final health check
      uri:
        url: "https://{{ domain_name }}/health"
        method: GET
        status_code: 200
        validate_certs: yes
      register: health_check
      retries: 3
      delay: 5
      until: health_check.status == 200
      tags: [verify]
    
    - name: Print deployment success message
      debug:
        msg: 
          - "LiteLLM has been successfully deployed with SSL!"
          - "Access your API at: https://{{ domain_name }}"
          - "Health check endpoint: https://{{ domain_name }}/health"
      tags: [verify]
